### ISSUE TITLE
Make clear whether this repo is ready for production use.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-country-and-territory-autocomplete#22]
Is this repo ready for production use? If not, we should be explicit about it.

The accessible autocomplete has not had a follow up accessibility audit - a step I feel should happen. I'm also not sure we have a good process for continually supporting it. Until those things are in place, should it be used in production?

**Comment by danmitchell-** [comment]
I _think_ this repo is production ready but I agree the https://github.com/alphagov/accessible-autocomplete needs to be audited again.

**Comment by nickcolley** [comment]
I think when this project is updated to the 2.0.0 release of the autocomplete it'll be suitable for production...
