### ISSUE TITLE
Make clear how this repo relates to accessible autocomplete

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-country-and-territory-autocomplete#23]
I don't think it's clear how this repo relates to accessible autocomplete. Both should be clear.

I've come across two cases of GDS teams using the accessible autocomplete when they probably wanted to be using this repo. Can we make the differences and the link between them clearer?

**Comment by danmitchell-** [comment]
I think this PR make it more obvious https://github.com/alphagov/govuk-country-and-territory-autocomplete/pull/24

**Comment by edwardhorsford** [comment]
Hi @danmitchell- I'm not sure how #24 makes it clearer. #alphagov/accessible-autocomplete doesn't seem to be mentioned in the readme.

**Comment by danmitchell-** [comment]
@J-Lambo prehaps something you could look into? 👀
