### ISSUE TITLE
update to use accessible-autocomplete 1.6.1

### ISSUE THREAD

**Issue by revilossor** [alphagov/govuk-country-and-territory-autocomplete#27]
hiya - could you please update the version of accessible-autocomplete to 1.6.1? Theres a bugfix in there we need. 

Also, could you publish a new version to npm? 

Thanks.

**Comment by danmitchell-** [comment]
Hi @revilossor, PR is open :) https://github.com/alphagov/govuk-country-and-territory-autocomplete/pull/26

**Comment by danmitchell-** [comment]
Merged and published @revilossor
