### ISSUE TITLE
Should this repo be renamed?

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-country-and-territory-autocomplete#3]
Should this repo be called openregister-location-picker?

Possible suggestions: 
**govuk-country-and-territory-autocomplete**
**govuk-country-and-territory-picker**
**govuk-country-territory-autocomplete**
**govuk-country-territory-picker**

Thoughts?

**Comment by tvararu** [comment]
> govuk-country-and-territory-autocomplete

This is my favourite of those two but I don't mind either way.

**Comment by danmitchell-** [comment]
+1 to `govuk-country-and-territory-autocomplete`. Will talk to the PM
