### ISSUE TITLE
Deleting country from input field does not reset select value

### ISSUE THREAD

**Issue by Kerrzinga** [alphagov/govuk-country-and-territory-autocomplete#46]
**To reproduce:** 
On a form with the country picker, 
type "fr" into country picker, 
select "france", 
delete "france" from the input field,
submit the form

**Actual outcome**
The country value will be "france"

**Expected outcome:**
The country value should be ""

**Comment by nubz** [comment]
We have just run into this issue too - there seems to be no handling of the change event when it's an empty string...

**Comment by nubz** [comment]
Actually this looks like it's an issue with accessible-autocomplete https://github.com/alphagov/accessible-autocomplete/issues/260

**Comment by nickcolley** [comment]
Thanks for the spot @nubz closing this out here. :)
