### ISSUE TITLE
Use latest version of accessibile-autocomplete to fix invalid use of SPAN wrapper

### ISSUE THREAD

**Issue by nubz** [alphagov/govuk-country-and-territory-autocomplete#69]
https://github.com/alphagov/accessible-autocomplete/pull/407 fixes the use of a SPAN element by accessible-autocomplete to wrap the enhanced element - using a span to wrap a div is being flagged as invalid HTML by our automated accessibility checks. SPAN's can only contain flow content or phrasing content.

Updating the version of accessible-autocomplete to v2.0.2 will fix this.

**Comment by 36degrees** [comment]
I believe this was resolved by #108
